### ISSUE TITLE
可以支持下青龙面板运行吗?

### ISSUE THREAD

**Issue by FairyWorld** [XiaoMiku01/fansMedalHelper#1]
可以支持下青龙面板运行吗?

**Comment by XiaoMiku01** [comment]
看了一下，青龙面板的gcc依赖有点问题，导致aiohttp库无法安装，目前暂不支持

**Comment by FairyWorld** [comment]
> 看了一下，青龙面板的gcc依赖有点问题，导致aiohttp库无法安装，目前暂不支持

是的，青龙面板安装aiohttp经常报错，我之前跑另一个脚本在这里卡住了很久，后来好像是通过在终端python -m pip install --upgrade pip，升级了一下青龙pip的版本，就可以安装aiohttp就不报错了

**Comment by XiaoMiku01** [comment]
https://xiaomiku01.github.io/fansMedalHelperVersion/guide/other.html 文档已更新
