### ISSUE TITLE
正在佩戴的牌子有概率不进行每日65分钟任务

### ISSUE THREAD

**Issue by trytodupe** [XiaoMiku01/fansMedalHelper#101]
使用的阿里云云函数 还没有测试外部调用
在我挂的6个账号里 4个账号出现了这个问题 （昨天是5个
我看了一下logs 这些账号未满1500亲密度的牌子数比正确值少了1 并且少的那个是正在佩戴的牌子
可能在判断牌子是否满1500亲密度的时候出了问题

我设置的触发器是北京时间6点 昨天和今天都出现了这个问题
但是我重新设置一个临时触发器 它就能正确判断牌子是否满1500亲密度

**Comment by FadeJay** [comment]
有同样的bug

**Comment by LMWC** [comment]
我也是，更新到0.3.6后，佩戴的粉丝牌不参加‘’每日观看xx分钟‘’这一项的执行

**Comment by XiaoMiku01** [comment]
收到，排查中，暂时解决方案：设置俩个定时器

**Comment by XiaoMiku01** [comment]
找到原因了，正在佩戴的牌子亲密度刷新有延迟，要比没带的牌子清零慢，或者手动去摘下牌子再带上刷新请密度。目前解决方案是默认将正在佩戴的牌子加入任务列表  
 [61a2fb9](https://github.com/XiaoMiku01/fansMedalHelper/commit/61a2fb9feb9cd059470c817a9d32f5ccfae9114f)   
已更新

**Comment by LMWC** [comment]
可以了，能正常执行
