### ISSUE TITLE
[Bug]: 领取电池失败：领取失败，请重试

### ISSUE THREAD

**Issue by RAINighty** [XiaoMiku01/fansMedalHelper#103]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 部署方式

本地

### 日志记录（可选）

```python
2022-12-12 00:29:11  为颜绎而生  领取电池失败: 领取失败，请重试
```

### 补充说明（可选）

```
USERS:
    - access_key: xxxx # 注意冒号后的空格 否则会读取失败 英文冒号
      white_uid: 0 # 白名单用户ID, 可以是多个用户ID, 以逗号分隔,填写后只会打卡这些用户,黑名单失效，不用就填0
      banned_uid: 0 # 黑名单UID 同上,填了后将不会打卡，点赞，分享 用英文逗号分隔 不填则不限制,两个都填0则不限制,打卡所有直播间
    - access_key: xxxx
      white_uid: 0
      banned_uid: 0
    # 注意对齐
    # 多用户以上格式添加
    # 井号后为注释 井号前后必须有空格！井号前后必须有空格！井号前后必须有空格！
    # 冒号后面也要有空格！冒号前面也要有空格！冒号前面也要有空格！
    # 英文冒号,英文逗号！英文逗号！英文逗号！
CRON: 0 0 * * *
# 这里是 cron 表达式, 第一个参数是分钟, 第二个参数是小时
# 例如每天凌晨0点0分执行一次为 0 0 * * *
# 如果不填,则不使用内置定时器,填写正确后要保持该进程一直运行

SENDKEY: # Server酱微信推送 可选 获取地址：https://sct.ftqq.com/
MOREPUSH: # 更多种类的推送 详细配置见文档

PROXY: # 推送代理地址,如：http://1.2.3.4:5678 支持 http/socks4/socks5 不支持 https 不用代理的不用填
#########以下为自定义配置#########

ASYNC: 0 # 异步执行,默认异步执行,设置为0则同步执行,开启异步后,将不支持设置点赞CD时间

LIKE_CD: 2 # 点赞间隔时间,单位秒,默认2秒,仅为同步时生效,设置为0则不点赞

DANMAKU_CD: 6 # 弹幕间隔时间,单位秒,默认6秒,设置为0则不发弹幕打卡,只能同步打卡

WATCHINGLIVE: 65 # 每日观看直播时长，单位 min ，设置为0则关闭, 默认 65 分钟

WEARMEDAL: 1 # 是否弹幕打卡时自动带上当前房间的粉丝牌，避免房间有粉丝牌等级禁言，默认关闭，设置为1则开启

SIGNINGROUP: 2 # 应援团签到CD时间,单位秒,默认2秒,设置为0则不签到
# 说明：
# 本项目中的异步执行指的是：同时点赞或者分享所有直播间，速度非常快，但缺点就是可能会被B站吞掉亲密度，所以建议粉丝牌较少的用户开启异步执行
# 粉丝牌数大于30的用户建议使用同步，会更加稳定。缺点就是速度比较慢，但是可以设置点赞和分享的CD时间，避免被B站吞掉亲密度
# 多用户之间依然是异步，不受配置影响
```

**Comment by XiaoMiku01** [comment]
几个粉丝牌

**Comment by XiaoMiku01** [comment]
B站还有这活动吗？我怎么没看到入口了

**Comment by zer02zero** [comment]
> B站还有这活动吗？我怎么没看到入口了

上周还有 这周应该是下线了 还没嫖几个牌子呢就下了

**Comment by Huli-fox** [comment]
### 粉丝牌助手 版本  
0.3.6([commit dcf4910](https://github.com/XiaoMiku01/fansMedalHelper/commit/dcf49108fe46e2a6e2d7e9930b41e0033f9ba16e))  
### 部署方式  
阿里云函数  
### 粉丝牌数量  
20  
### 日志记录
![屏幕截图 2023-01-07 205657.png](https://s2.loli.net/2023/01/07/jmL8fpx2aQkI4gy.png)

**Comment by XiaoMiku01** [comment]
> ### 粉丝牌助手 版本
> 0.3.6([commit dcf4910](https://github.com/XiaoMiku01/fansMedalHelper/commit/dcf49108fe46e2a6e2d7e9930b41e0033f9ba16e))
> 
> ### 部署方式
> 阿里云函数
> 
> ### 粉丝牌数量
> 20
> 
> ### 日志记录
> ![屏幕截图 2023-01-07 205657.png](https://camo.githubusercontent.com/b59f84194e16b411e73bf9b14efabec0b6a3f59e6cf1894c5f78c96ba380e00b/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30312f30372f6a6d4c386670783261516b493467792e706e67)

手动去领试试
