### ISSUE TITLE
[Bug]: 开始运行时报了个错

### ISSUE THREAD

**Issue by Haibara-cx** [XiaoMiku01/fansMedalHelper#104]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

本地

### 粉丝牌数量

74

### 补充说明（可选）

![20221214182539](https://user-images.githubusercontent.com/67082179/207570496-8f6a004b-1795-47c5-9ca2-e04916de7926.png)

**Comment by XiaoMiku01** [comment]
图片打不开

**Comment by Haibara-cx** [comment]
つき
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMiku01/fansMedalHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 晚上9:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [XiaoMiku01/fansMedalHelper] [Bug]: 开始运行时报了个错 (Issue #104)





 
图片打不开

**Comment by Haibara-cx** [comment]
つき
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "XiaoMiku01/fansMedalHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 晚上9:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [XiaoMiku01/fansMedalHelper] [Bug]: 开始运行时报了个错 (Issue #104)





 
图片打不开

**Comment by Haibara-cx** [comment]
![屏幕截图 2022-12-14 212607](https://user-images.githubusercontent.com/67082179/207747961-81ef72a5-2d58-4392-9e95-5c00ee43cce5.png)

**Comment by Haibara-cx** [comment]
大佬 不好意思 我自己的问题 已经解决了
