### ISSUE TITLE
可以做一个arm64架构的docker镜像吗

### ISSUE THREAD

**Issue by ngoiakarin** [XiaoMiku01/fansMedalHelper#105]
**需要添加的功能内容**

可以做一个arm64架构的docker镜像吗

**Comment by paradox8599** [comment]
这个镜像好像没什么复杂的地方，只是用 python 镜像安装 git 然后 `git clone`, `pip install`。你可以考虑自己做一个。
[arm64v8/python:3.9-slim](https://hub.docker.com/r/arm64v8/python/tags?page=1&name=3.9-slim)
