### ISSUE TITLE
青龙面板有奇怪符号

### ISSUE THREAD

**Issue by ilhmtfmlt2** [XiaoMiku01/fansMedalHelper#106]
**环境信息**

`粉丝牌助手版本:`最新版

**需要添加的功能内容**

可能是我的操作问题，造成了当前的显示，我尝试过很多次但没有解决问题
[32m2023-01-03 05:05:57[0m [34m类似这样的字符
![cafc0ada36b69dcfc081585a019b9b0](https://user-images.githubusercontent.com/83404297/210278309-2b781e07-a19b-4cbf-a4e4-c86107360696.png)

**Comment by XiaoMiku01** [comment]
显示问题不影响

**Comment by tang-guo-guo** [comment]
编码问题,能用就不管
