### ISSUE TITLE
关于 Docker 版本目前存在的一些问题

### ISSUE THREAD

**Issue by Xm798** [XiaoMiku01/fansMedalHelper#109]
本来想开个 PR 尝试 fix 一下 #108 ，看到本项目不接受 PR，就从我的角度说一下 Docker 方面感觉存在的问题。

1. 镜像完全可以换为 `python:3.9-alpine`，现在一个 80M 的镜像属实是太大了。
2. 既然在 `main.py` 中有 load 配置文件，那么 Docker 入口也可以调整为 `main.py`。现在在 `index.py` 入口中调用 `os` 再启动一个 python，也没有存在的必要。 
3. `user.yaml` 应当在 `gitignore` 中忽略，提供 `user.example.yaml` 供示例使用，现在的做法导致 gitignore 无法生效，更新只能粗暴的删除镜像/删除仓库，为了一个配置文件采取这种更新方式，有些得不偿失，且不太符合规范。
4. Docker 应支持映射配置文件的方式，受到第三点的影响，无法正常映射配置文件和使用 git pull。#44 提到的问题就是 3 的后遗症，该问题不应粗暴采用删除容器的方法来解决，用户配置文件本就属于应被 git 忽略的项目。
5. #105 提到的多架构镜像，可以采用 GitHub Aciton 自动构建，无需手动构建。

**Comment by Xm798** [comment]
使用 GitHub Action 构建 Docker 镜像的示例，供您参考。

https://github.com/Xm798/Genshin-Dailynote-Reminder/blob/master/.github/workflows/dockers.yaml

**Comment by XiaoMiku01** [comment]
欢迎pr，docker的版本是历史遗留问题，当时随便写的，我也不太熟悉写dockerfile
