### ISSUE TITLE
[青龙]Failed building wheel for backports.zoneinfo Failed to build backports.zoneinfo

### ISSUE THREAD

**Issue by ChristopherSung** [XiaoMiku01/fansMedalHelper#110]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

青龙

### 运行架构

None

### 部署方式

其它（请在下方说明）

### 粉丝牌数量

27

### 补充说明（可选）

![2023-01-20_135259](https://user-images.githubusercontent.com/49830879/213627860-145f1d70-5f50-495b-bc9c-6a9dc06dde1d.png)

**Comment by XiaoMiku01** [comment]
自行在青龙面板里面安装一下 gcc 环境

**Comment by ChristopherSung** [comment]
**补充**
添加gcc后报错图
![3IUGQ6G`QI00D%4H50F8O6W](https://user-images.githubusercontent.com/49830879/213665251-1a233a10-98a0-4368-907f-27d625cf5dd9.png)

**解决方法**
进入青龙容器
`docker exec -it qinglong bash`执行`apk add python3-dev gcc libc-dev`
