### ISSUE TITLE
可以支持gocqhttp的push嘛，因为现在QQbot还挺多用处的

### ISSUE THREAD

**Issue by ayakasuki** [XiaoMiku01/fansMedalHelper#111]
**环境信息**

docker,python3.9,debian
粉丝牌助手版本:最新版

**需要添加的功能内容**

![image](https://user-images.githubusercontent.com/20859971/214558910-11d1d5d8-3b3f-4cd1-a72b-4906aa6abf43.png)
类似一些游戏签到的脚本push，也是有send_msg这种api窗口的

**Comment by ayakasuki** [comment]
而且这个东西也是y1ndan的原神签到，哈哈

**Comment by ayakasuki** [comment]
我看到了onepush里面是有gocqhttp.py的 但是设置以后推送没有反应，
![image](https://user-images.githubusercontent.com/20859971/214569192-44166e49-d05e-4b22-bfc7-81a44a751ff3.png)
显示这个来着

**Comment by ayakasuki** [comment]
已修复 gh pr checkout 78

**Comment by ayakasuki** [comment]
已修复 #78

**Comment by XiaoMiku01** [comment]
重新pr一个过来，#78 有点乱。不要添加新的库，就用aiohttp
