### ISSUE TITLE
本地部署相关

### ISSUE THREAD

**Issue by realYXT** [XiaoMiku01/fansMedalHelper#112]
您好，我是计算机小白，采用了本地部署的方式，在user.yaml里设置了cron时间。
想问一下，如果我想每日自动打卡，需要后台一直挂着main.py吗或者每日手动打开main.py？能不能教教我如何到了我设定的时间，main.py会自动打开运行。
谢谢。

**Comment by realYXT** [comment]
我在b站查到可以使用windows自带的计划任务程序，是这样吗？BV1vt4y1C7kE

**Comment by XiaoMiku01** [comment]
小白就用云函数，其他的和我没关系
