### ISSUE TITLE
[Bug]: b站api有时不会正确返回json

### ISSUE THREAD

**Issue by trytodupe** [XiaoMiku01/fansMedalHelper#114]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

最新版 dcf4910

### 运行环境

Linux (云函数)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

6个账户 最多的23个

### 日志记录（可选）

```python
任务执行失败: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://live-trace.bilibili.com/xlive/data-interface/v1/heartbeat/mobileHeartBeat')
```

### 补充说明（可选）

这个错误我见到过了四次 但是间隔时间都很长 所以我现在才开了这个issue 我记录的两次分别获得了1010和510亲密度

错误是在发送心跳包时出现的 出错后程序会推送消息并结束运行

这个api返回的结果我不知道是什么 也许可以先把返回的结果log一下 或者忽略这个错误？

**Comment by XiaoMiku01** [comment]
同时挂的号太多了，被B站拦截了

**Comment by trytodupe** [comment]
我设置的早上6点运行 近三天连续出现了这个问题 但是我在晚上10点左右手动设置触发器就可以拿满亲密度 可能时间也会有影响 我再尝试几天

**Comment by trytodupe** [comment]
改成晚上10点之后连续拿满了4天 问题算是解决了
