### ISSUE TITLE
[Bug]: 亲密度只能拿到200或者300了

### ISSUE THREAD

**Issue by KNaiFen** [XiaoMiku01/fansMedalHelper#118]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

本地

### 粉丝牌数量

206

### 补充说明（可选）

日志记录一切正常，没报错
貌似是因为粉丝牌数量太多了？前一阵子没这个问题，上了200之后才这样，不过也不确定是不是因为B站有什么更新了

**Comment by XiaoMiku01** [comment]
似乎就是粉丝牌太多了。

**Comment by MaouSanta** [comment]
我在腾讯云上部署的，发现只有我佩戴的粉丝牌出现了不满的情况。看了近七天的日志，发现奇数日不满，偶数日满，不知道是不是有这部分的问题

**Comment by pjy612** [comment]
我一般 挂两波，10点一次，15点一次.

**Comment by XiaoMiku01** [comment]
行，我看看

**Comment by pjy612** [comment]
> 行，我看看

囧 发现不是作者改的。。。是 pr 。。。给跪。。。

**Comment by XiaoMiku01** [comment]
> > 行，我看看
> 
> 囧 发现不是作者改的。。。是 pr 。。。给跪。。。

已经恢复了单次执行模式了。github action 慎用，容易封仓库，或封号，特别是本项目会发送大量的第三方网络请求，更容易导致封号
