### ISSUE TITLE
还会推出云函数版本吗？目前发现只有百度云有免费额度了

### ISSUE THREAD

**Issue by xwfer** [XiaoMiku01/fansMedalHelper#12]

**Comment by XiaoMiku01** [comment]
百度云的Python版本是3.6，目前没适配

**Comment by Sunday808** [comment]
免费额度阿里华为都有吧
https://help.aliyun.com/document_detail/54301.html
https://support.huaweicloud.com/productdesc-functiongraph/functiongraph_01_0190.html

**Comment by xwfer** [comment]
> 免费赠送阿里华为吧有 [https://help.aliyun.com/document_detail/54301.html ](https://help.aliyun.com/document_detail/54301.html) https://support.huaweicloud.com/productdesc-functiongraph/functiongraph_01_0190.html

调用次数和执行时长有免费额度，如果想用Server酱推送，只有百度云有公网流量免费额度

**Comment by XiaoMiku01** [comment]
> 

阿里的似乎会抹零，如果一个月用的少的话也是不收钱的，不过暂时没去测试

**Comment by xwfer** [comment]
我用了一星期百度云的函数计算，还可以，调用次数、资源使用、公网流量的免费额度写的很清楚 https://cloud.baidu.com/product-price/cfc.html

**Comment by XiaoMiku01** [comment]
已经推出阿里云版本，百度的执行时间不够

**Comment by xwfer** [comment]
辛苦了
