### ISSUE TITLE
[Bug]: 腾讯云函数和阿里应用创建失败

### ISSUE THREAD

**Issue by Tianzhen1016** [XiaoMiku01/fansMedalHelper#120]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

腾讯云函数

### 粉丝牌数量

5

### 日志记录（可选）

```python
腾讯函数{

  "errorCode": 1,

  "errorMessage": "Function is Unavailable, AvailableStatus = InsufficientBalance.",

  "requestId": "e1759c85-0bb1-4d40-b443-919873dc64cc",

  "statusCode": 410

}
```

### 补充说明（可选）

阿里应用现在开通了流水线，要求选择一个触发？然后部署失败，希望大佬更新下方法

**Comment by pjy612** [comment]
把 main.py 改改 直接挂 GitHub 上

**Comment by XiaoMiku01** [comment]
https://github.com/XiaoMiku01/fansMedalHelper/commit/08ddeeebad8cd5cb87b4127b818a878cf39773f4 已修复

**Comment by Tianzhen1016** [comment]
> 把 main.py 改 直接挂 GitHub 上

。。。看了下，超出理解了

**Comment by XiaoMiku01** [comment]
重新同步上游仓库
