### ISSUE TITLE
疑惑 强制将佩戴的勋章放入队列

### ISSUE THREAD

**Issue by pjy612** [XiaoMiku01/fansMedalHelper#121]
https://github.com/XiaoMiku01/fansMedalHelper/blob/1094a6b8e317065c1d7a14c861b95e86c92a685c/src/api.py#L156

这段 似乎会导致，佩戴的勋章即使亲密度满了 也会触发强制观看 和 消息提醒中处于不满的列表中，实际又满了。
是有什么深意吗？

**Comment by XiaoMiku01** [comment]
因为前段时间，当时佩戴的粉丝牌，0点刚刷新请密度的时候，会比没带的牌子要慢刷新，依然是前一天的。所以就强制添加到队列了
