### ISSUE TITLE
[Bug]: 阿里云部署成功运行，但开启自动更新遇到错误

### ISSUE THREAD

**Issue by aichixiaojuzi** [XiaoMiku01/fansMedalHelper#125]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Linux (云函数)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

56

### 日志记录（可选）

```python
Error: Failed to create or merge pull request: HttpError: Resource not accessible by integration
```

### 补充说明（可选）

![Snipaste_2023-03-15_08-23-02](https://user-images.githubusercontent.com/43509012/225173156-142f83e6-8a91-4244-971f-1e15885166a4.jpg)

**Comment by XiaoMiku01** [comment]
这是同步上游仓库报错了，问题不大，不想同步关了就行

**Comment by aichixiaojuzi** [comment]
明白了，已关同步，感谢解答
