### ISSUE TITLE
[Bug]: 腾讯云函数部署错误

### ISSUE THREAD

**Issue by JamYiz** [XiaoMiku01/fansMedalHelper#126]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Linux (云函数)

### 运行架构

None

### 部署方式

腾讯云函数

### 粉丝牌数量

9

### 日志记录（可选）

```python
sh-4.2# rm -rf src && cd src            
sh: cd: src: No such file or directory
sh-4.2# git clone https://github.com/XiaoMiku01/fansMedalHelper.git ./
fatal: destination path '.' already exists and is not an empty directory.
sh-4.2# cp users.example.yaml users.yaml
cp: cannot stat 'users.example.yaml': No such file or directory
sh-4.2# python3 -m pip install --upgrade pip
sh: python3: command not found
sh-4.2# pip3 install -t . -r requirements.txt
sh: pip3: command not found
sh-4.2#
```

**Comment by XiaoMiku01** [comment]
不会处理的就是阿里云的一键部署

**Comment by cjdgyyy** [comment]
> 

啥意思 要去用阿里云部署吗
