### ISSUE TITLE
现在每天观看新主播并发弹幕可以获得1电池，每天可以获得20电池，能否考虑加上自动完成这个任务的功能

### ISSUE THREAD

**Issue by polarabbit0** [XiaoMiku01/fansMedalHelper#128]
**环境信息**

粉丝牌助手版本:

**需要添加的功能内容**
现在每天观看新主播并发弹幕可以获得1电池，每天可以获得20电池，能否考虑加上自动完成这个任务的功能

**Comment by XiaoMiku01** [comment]
有无活动链接

**Comment by polarabbit0** [comment]
![QQ图片20230321184407](https://user-images.githubusercontent.com/86583346/226584224-a5ad2d47-3a1a-49bb-8dd9-0a693a86ed9c.jpg)
![QQ图片20230321184413](https://user-images.githubusercontent.com/86583346/226584244-0e533cb7-23ee-4644-9e10-b8ea6342d85e.jpg)

**Comment by XiaoMiku01** [comment]
这要看号吧，我这没有

**Comment by 36EMiyuki** [comment]
我没有这个诶

**Comment by RAINighty** [comment]
![Screenshot_2023-07-23-19-11-03-20_149003a2d400f6a](https://github.com/XiaoMiku01/fansMedalHelper/assets/97167694/f723907a-56ac-47dd-83d9-2ea9b864f78a)
