### ISSUE TITLE
[Bug]: 已注销账户是否存在风险问题+pr请求

### ISSUE THREAD

**Issue by Agnes4m** [XiaoMiku01/fansMedalHelper#129]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 部署方式

本地

### 粉丝牌数量

30

## 风险:注销主播牌子？
![image](https://user-images.githubusercontent.com/70925546/231067974-4e10994b-db18-4387-bc76-84319b68999f.png)
测试的时候，发现已注销的主播的牌子，也会提示打卡成功，我不清楚是否真的打卡成功了，但是我知道这样看起来很有风险。如果您了解这方面可能存在的风险，或者不存在风险，希望可以说明

## pr请求
其中的登录程序我用python改写了，如果可以，我希望pr这个（因为github下载那个exe着实有点慢，不够方便）。
我遵守GPLV3开源许可证原则开源项目，希望可以为一个机器人框架[nonebot2](https://v2.nonebot.dev/)改写这个项目作为插件。

**Comment by XiaoMiku01** [comment]
有啥风险？没必要用python,当初用go写的原因就是想可以跨平台和不用自己准备环境，例如小白用阿里云函数部署只需要下载登录器扫码登录就行，如果用python的话还需要自己准备python环境

**Comment by Agnes4m** [comment]
因为已经注销的用户，虽然我保留了他的牌子，但是他的主页和直播间都是没办法访问的。

我不确定是不是提示有问题，如果真的如提示，访问了不存在的直播间打卡发弹幕，那是否有点诡异？

**Comment by XiaoMiku01** [comment]
叔叔又不管，管他呢，不想打卡的写黑名单里
