### ISSUE TITLE
功能建议：添加人气票自动获取和赠送

### ISSUE THREAD

**Issue by haishen668** [XiaoMiku01/fansMedalHelper#134]
**环境信息**python3.7

粉丝牌助手版本:0.3.6

**哔哩哔哩有个东西叫做人气票，每五分钟都能获得一定免费人气票，这个脚本挂播他不能获取人气票，不懂为什么**
我希望能定时自动赠送人气票，并且有获取人气票的功能

**Comment by pjy612** [comment]
人气票 那个东西似乎不能同时获取。另外是打算24小时挂吗？
感觉这个功能做成浏览器插件反而比较靠谱。。。看的时候 自动检查 是不是有，有了就送掉。

**Comment by haishen668** [comment]
> 人气票 那个东西似乎不能同时获取。另外是打算24小时挂吗？ 感觉这个功能做成浏览器插件反而比较靠谱。。。看的时候 自动检查 是不是有，有了就送掉。

我是想等开播的时候自动挂票，然后定点（比如每天下午一点）一起送，这样才可以和大主播竞争，作者这个他在挂播的时候不能获取人气票，不懂为什么。

**Comment by pjy612** [comment]
主要是 也没见其他能挂人气票的啊 = =。

**Comment by gy39830** [comment]
能挂，不过要主播开播的时候才有用

**Comment by Tiexcn** [comment]
确实 挂机主要是想挂点人气票，

**Comment by XiaoMiku01** [comment]
这样还需要检查主播有没有开播。比较麻烦，以后考虑加入

**Comment by XiaoMiku01** [comment]
复杂功能 不加了

**Comment by XiaoMiku01** [comment]
我懒
