### ISSUE TITLE
[Error]: 点赞任务异常

### ISSUE THREAD

**Issue by olencer** [XiaoMiku01/fansMedalHelper#136]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

v0.3.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 部署方式

本地

### 粉丝牌数量

9

### 日志记录（可选）

```python
src.api.BiliApiError: Key: 'LikeReportV3Req.ClickTime' Error:Field validation for 'ClickTime' failed on the 'required' tag.
```

**Comment by olencer** [comment]
![1692856298319](https://github.com/XiaoMiku01/fansMedalHelper/assets/47381894/c2b2c9af-8116-4ffa-ba7e-264053e0a972)

**Comment by olencer** [comment]
第一次fork，pull，等我研究一下。

**Comment by hhsjja** [comment]
解决了吗？我这两天也是点赞任务异常

**Comment by olencer** [comment]
> 解决了吗？我这两天也是点赞任务异常

我打算明天再测试后merge。
你也可以自己试试，替换一下把 \src\api.py文件(记得备份)替换成 https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py文件。
你也可以用的话，我就直接merge了。

**Comment by olencer** [comment]
> > 解决了吗？我这两天也是点赞任务异常
> 
> 我打算明天再测试后merge。 你也可以自己试试，替换一下把 \src\api.py文件(记得备份)替换成 [https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py文件。](https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py%E6%96%87%E4%BB%B6%E3%80%82) 你也可以用的话，我就直接merge了。

[https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py](https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py%E6%96%87%E4%BB%B6%E3%80%82)

**Comment by olencer** [comment]
> > > 解决了吗？我这两天也是点赞任务异常
> > 
> > 
> > 我打算明天再测试后merge。 你也可以自己试试，替换一下把 \src\api.py文件(记得备份)替换成 [https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py文件。](https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py%E6%96%87%E4%BB%B6%E3%80%82) 你也可以用的话，我就直接merge了。
> 
>点这个，没y [https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py](https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py)



> > > 解决了吗？我这两天也是点赞任务异常
> > 
> > 
> > 我打算明天再测试后merge。 你也可以自己试试，替换一下把 \src\api.py文件(记得备份)替换成 [https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py文件。](https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py%E6%96%87%E4%BB%B6%E3%80%82) 你也可以用的话，我就直接merge了。
> 
> [https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py](https://github.com/olencer/fansMedalHelper/blob/fix_like_task/src/api.py)

点这个，前面两个错了，没习惯github的评论系统。。。
