### ISSUE TITLE
[Bug]: 【To Reproduce】{Discussion}

### ISSUE THREAD

**Issue by zhaoniubi** [XiaoMiku01/fansMedalHelper#138]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

最新2023/8/25

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

26

### 日志记录（可选）

```python
File "/code/src/user.py", line 195, in like_v3
    await asyncio.gather(*allTasks)
...
src.api.BiliApiError: Key: 'LikeReportV3Req.ClickTime' Error:Field validation for 'ClickTime' failed on the 'required' tag

这段错误信息表明在某个代码运行过程中发生了问题。它似乎是与一个名为BiliApi的类相关的，涉及到点赞任务。具体来说，它提到了一个字段名为'LikeReportV3Req.ClickTime'，并表示在必需的标签上进行了'ClickTime'字段的验证失败。
```

### 补充说明（可选）

来自gpt

抱歉啊

_不太会提问_

**Comment by XiaoMiku01** [comment]
更新，昨天就解决了

**Comment by zhaoniubi** [comment]
OK
