### ISSUE TITLE
找不到"Enable workflow"按钮

### ISSUE THREAD

**Issue by zhaoniubi** [XiaoMiku01/fansMedalHelper#139]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

最新2023/8/25

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

26

### 补充说明（可选）

![image](https://github.com/XiaoMiku01/fansMedalHelper/assets/91838298/755e0fa1-768c-4f2a-a1f6-19b26449836f)

非常抱歉
找了很久
重新做了应用一遍、、
还是这样

**Comment by zhaoniubi** [comment]
还是不会

**Comment by XiaoMiku01** [comment]
删了，重新fork 部署

**Comment by zhaoniubi** [comment]
ok
