### ISSUE TITLE
无法获得access_key

### ISSUE THREAD

**Issue by bonnie-ch** [XiaoMiku01/fansMedalHelper#14]
苹果M1芯片系统，打开login_darwin_arm64显示乱码，请问是怎么回事呢？谢谢！

<img width="685" alt="Screen Shot 2022-05-26 at 15 21 46" src="https://user-images.githubusercontent.com/49169940/170439877-56200d6a-4e7e-4aa8-a501-e7a5d0456b95.png">

**Comment by XiaoMiku01** [comment]
找个windows机子试试吧，我手里没有苹果机

**Comment by ThreeCatsLoveFish** [comment]
> 苹果M1芯片系统，打开login_darwin_arm64显示乱码，请问是怎么回事呢？谢谢！
> 
> <img alt="Screen Shot 2022-05-26 at 15 21 46" width="685" src="https://user-images.githubusercontent.com/49169940/170439877-56200d6a-4e7e-4aa8-a501-e7a5d0456b95.png">

没有windows不嫌麻烦可以装个go环境，运行下 go run login.go也可以

**Comment by bonnie-ch** [comment]
> 找个windows机子试试吧，我手里没有苹果机

找有Windows机子的朋友帮忙成功了，谢谢！
