### ISSUE TITLE
[Error]: 点赞任务异常

### ISSUE THREAD

**Issue by trytodupe** [XiaoMiku01/fansMedalHelper#143]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.7

### 运行环境

Linux (云函数)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

7个账号 2-30个不等

### 日志记录（可选）

```python
点赞任务异常
src.api.BiliApiError: Key: 'LikeReportV3Req.Uid' Error:Field validation for 'Uid' failed on the 'required' tag
```

**Comment by XiaoMiku01** [comment]
没看到昨天的提交吗 https://github.com/XiaoMiku01/fansMedalHelper/commit/9772d1392d4572e5201443597dc17e5800a7a912

**Comment by trytodupe** [comment]
不好意思 上次看的时候还没有这个commit 今天开issue的时候没注意
