### ISSUE TITLE
[Bug]:  我测试的直播间牌子总提示已满1500，无法直播间正常挂机。

### ISSUE THREAD

**Issue by Tiexcn** [XiaoMiku01/fansMedalHelper#146]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

 0.3.7

### 运行环境

Windows (64)

### 运行架构

x86

### 部署方式

本地

### 粉丝牌数量

2，10，25

### 补充说明（可选）

测试前一天，因为一电脑挂机，所以可能是满了1500的，但是过了0点，应该刷新了，还是提示1500，没办法继续直播间挂机

![image](https://github.com/XiaoMiku01/fansMedalHelper/assets/20148078/bc62426b-0de6-4e69-9b13-37525a4d5d90)

**Comment by Tiexcn** [comment]
2个舰长号，1个非舰，结果显示一样。

**Comment by XiaoMiku01** [comment]
那就换个时间挂，等b亲密度重置

**Comment by Tiexcn** [comment]
> 那就换个时间挂，等b亲密度重置

我试了一下，其它的新号可以挂这个房间有心跳，我舰长号直接提示亲密度满了，这个脚本是不支持20及以上牌子的号么。

**Comment by XiaoMiku01** [comment]
对，20级以上就跳过了，本来20级以上就不加亲密度了

**Comment by Tiexcn** [comment]
> 对，20级以上就跳过了，本来20级以上就不加亲密度了

啊这，，，，这个挂机功能太好用了啊，电脑配置不高，只能挂一个号，挂多个号CPU直接100%，可怜的小电脑啊。。。。可否考虑给个开关来跳过这个限制啊。真的灰常感谢。。。。

**Comment by Tiexcn** [comment]
我尝试修改了这个文件里的第99行的等级和亲密度限制。好像可以正常挂机了，但如果有在users.yaml 留有相关选项会更方便吧，谢谢你提供的程序。帮我解决了大问题。

fansMedalHelper\src\user.py 
  if medal['medal']['level'] < 50 and medal['medal']['today_feed'] < 15000

**Comment by GOOD-AN** [comment]
20级以上获取亲密度的方式不是只有
- 投喂电池礼物/醒目留言/开通大航海：1电池=1航海亲密度
- 给视频充电：1B币=10航海亲密度

依据[帮助中心](https://link.bilibili.com/p/help/index#/audience-fans-medal)
