### ISSUE TITLE
想问一下，房间弹幕打卡的功能要怎么关掉啊？

### ISSUE THREAD

**Issue by Malus-Mill** [XiaoMiku01/fansMedalHelper#15]
![image](https://user-images.githubusercontent.com/53999738/170460985-dff8166c-fde0-42f6-aaf0-f600a43cec25.png)

**Comment by yizhibeibei** [comment]
https://github.com/XiaoMiku01/fansMedalHelper/blob/master/src/user.py
第156行改为 task = [self.likeandShare()]

**Comment by jjnnnh** [comment]
我按配置文件写了开关，按需开启
users.yaml
追加一行 DMDK: 0 # 弹幕打卡任务开关

main.py
startTasks.append(biliUser.start()) 改成 startTasks.append(biliUser.start(DMDK=users.get('DMDK', 0)))

src/user.py
async def init(self): 改成
async def start(self, DMDK: int = 0):

task = [self.likeandShare(), self.sendDanmaku()] 改成
task = [self.likeandShare()]
            if DMDK:
                task.append(self.sendDanmaku())
            else:
                self.log.log("WARNING", "弹幕打卡任务被禁用")

**Comment by XiaoMiku01** [comment]
新版本可以自定义了

**Comment by Malus-Mill** [comment]
> 新版本可以自定义了

!!!感谢大佬！！！
