### ISSUE TITLE
[Bug]: 正常使用呢，阿里云突然就这样报错了是什么原因

### ISSUE THREAD

**Issue by jasonwang1111** [XiaoMiku01/fansMedalHelper#156]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.7

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

43

### 日志记录（可选）

```python
FunctionCompute python3 runtime inited.
FC Invoke Start RequestId: 1-656c078f-9a0dcabc96fc7ba1dd85382a
2023-12-03 12:44:01  B站粉丝牌助手  读取配置文件失败,请检查配置文件格式是否正确: Expecting value: line 1 column 1 (char 0)
FC Invoke End RequestId: 1-656c078f-9a0dcabc96fc7ba1dd85382a, Error: Process exited unexpectedly before completing request (duration: 481ms, maxMemoryUsage: 26MB)
```

**Comment by XiaoMiku01** [comment]
字面意思

**Comment by darkwong1995** [comment]
相同情况, 请问怎么解决的?
