### ISSUE TITLE
[Bug]: 克隆(升级)不了,求指点

### ISSUE THREAD

**Issue by BlackSpacee** [XiaoMiku01/fansMedalHelper#161]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.8

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

27

### 日志记录（可选）

```python
更新(克隆)错误
```

### 补充说明（可选）

一直在用，挺好用的，昨天看到有问题第一时间也去更新了，然后一直克隆不下来，怎么换浏览器怎么换网络环境也没用，一直显示Failed to connect to github.com port 443: Connection timed out，看过一些设置本地代理的教程命令那些都无用。代理什么的都正常，不知道怎么解决了。关键是我本地git clone,git push什么的都可以，网络环境按道理应该也没问题啊。尝试很多次了，在那个云环境下一直超时，请问有人跟我一样的吗？

**Comment by BlackSpacee** [comment]
主要是换很多节点很多浏览器尝试很多次数了，不知道为啥，本地可以，那个云环境就不可以。很奇怪。难道真的我的网络原因吗

**Comment by baobao521o** [comment]
我更新了一下版本，有的可以弹幕打卡，有的还是不行，点赞一直不行

**Comment by XiaoMiku01** [comment]
> 主要是换很多节点很多浏览器尝试很多次数了，不知道为啥，本地可以，那个云环境就不可以。很奇怪。难道真的我的网络原因吗

删了函数重新部署试试

**Comment by liuruidong4** [comment]
我直接从gitee里更新就完事。
