### ISSUE TITLE
[Bug]: 获取access_key失败

### ISSUE THREAD

**Issue by SysuCodeRookie** [XiaoMiku01/fansMedalHelper#163]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.8

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

本地

### 粉丝牌数量

83

### 日志记录（可选）

```python
打开access_key获取工具后，可以正常生成登录二维码，但是扫描后命令行窗口立即闪退，并不能返回access_key以生成user.yaml
```

**Comment by XiaoMiku01** [comment]
看看当前目录下有没有生成txt文件
不然就试试这个
https://github.com/XiaoMiku01/fansMedalHelper/releases/tag/logintool
