### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by guyouhantan** [XiaoMiku01/fansMedalHelper#166]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.8

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

150

### 补充说明（可选）

使用阿里云更新时遇到
fatal: unable to access 'https://github.com/XiaoMiku01/fansMedalHelper.git/': Failed to connect to github.com port 443: Connection timed out
阿里云连不上github怎么办

**Comment by Aiko1737** [comment]
咋解决的老哥
