### ISSUE TITLE
[Bug]: 阿里云函数更新报错 fatal: unable to access 'https://github.com/XiaoMiku01/fansMedalHelper.git/': Failed to connect to github.com port 443: Connection timed out

### ISSUE THREAD

**Issue by Aiko1737** [XiaoMiku01/fansMedalHelper#167]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.7

### 运行环境

Windows (64)

### 运行架构

None

### 部署方式

阿里云函数

### 粉丝牌数量

98

### 日志记录（可选）

```python
git clone https://github.com/XiaoMiku01/fansMedalHelper.git && cp -rf fansMedalHelper/* . && pip3 install -t . -r requirements.txt && cp users.example.yaml users.yaml
Cloning into 'fansMedalHelper'...
fatal: unable to access 'https://github.com/XiaoMiku01/fansMedalHelper.git/': Failed to connect to github.com port 443: Connection timed out
```

### 补充说明（可选）

github能进，但是在云环境里clone不了，前面有个朋友也遇到了，但是我问他解决办法没回复。

**Comment by Aiko1737** [comment]
用gitee正常更新了，但还是好奇如何解决git clone，期待作者或者其他大佬能解释下

**Comment by XiaoMiku01** [comment]
最简单的方法就是删了重新部署 也不是什么麻烦事
