### ISSUE TITLE
关于使用Github的workflow来执行脚本的想法

### ISSUE THREAD

**Issue by wonoton** [XiaoMiku01/fansMedalHelper#182]
这个issue主要是做一个 #181   的解释
用户文档里面部署的部分已经很完善了，但是action毕竟不要钱，而且secrets的方式存储用户信息比明文的配置文件要安全
用户文档暂时没看到在哪里维护，如果有关于action使用的疑问或者用户文档需要更新可以联系我

执行截图
![`1SDU%3V3%}G5XUW9~KF(LW](https://github.com/XiaoMiku01/fansMedalHelper/assets/43060541/48226715-0a71-46c9-891b-ce78fac3c94f)

**Comment by XiaoMiku01** [comment]
不要钱但是违反了github使用条例,会被封仓库
https://docs.github.com/zh/site-policy/github-terms/github-terms-for-additional-products-and-features#a-actions-usage
