### ISSUE TITLE
这个是什么原因啊

### ISSUE THREAD

**Issue by shallowgit** [XiaoMiku01/fansMedalHelper#20]
虽然成功了，但是断断续续的
![Snipaste_2022-05-28_00-28-12](https://user-images.githubusercontent.com/53215019/170740848-1969c757-b5a7-4b96-9d75-96370a2fcdee.png)

**Comment by XiaoMiku01** [comment]
都这样，下面不是写了重试成功吗

**Comment by shallowgit** [comment]
> 都这样，下面不是写了重试成功吗

噢喔，好的，我以为是我哪里操作错了
