### ISSUE TITLE
机器人推送消息服务是不是寄了

### ISSUE THREAD

**Issue by nab11111** [XiaoMiku01/fansMedalHelper#209]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

0.3.8

### 运行环境

Ubuntu

### 运行架构

x86

### 部署方式

本地

### 粉丝牌数量

21

### 补充说明（可选）

![1](https://github.com/user-attachments/assets/aa82d140-a93c-4b9c-811e-e8dde1ba3a54)
如图一 我用手动让机器人发送了一条推送 是可以正常推送到我账号
![2](https://github.com/user-attachments/assets/a0df2b1b-c573-491d-bbfb-5565ba9a4894)
图二 我使用项目里的推送命令无法推送
![3](https://github.com/user-attachments/assets/19ee4608-4ce4-4d1e-bfce-81fcdd91eadf)
图三 为我的配置文件

**Comment by MoKuuy** [comment]
你是不是把地址填到注释里面去了(emoji
![微信截图_20241211173348](https://github.com/user-attachments/assets/c5c9f233-795c-46bc-8626-ba7211b31a23)
