### ISSUE TITLE
运行login_win.go出错

### ISSUE THREAD

**Issue by RnYi** [XiaoMiku01/fansMedalHelper#22]
哥，运行login_win.go的时候会报错：
panic: Post "http://passport.bilibili.com/x/passport-tv-login/qrcode/poll": http: ContentLength=129 with Body length 0

goroutine 1 【running】:
main.verify_login({0xc0000b6249, 0x20})
        C:/Tools/fansMedalHelper/logintool/login.go:109 +0xb36
main.loginBili()
        C:/Tools/fansMedalHelper/logintool/login.go:168 +0x24e
main.main()
        C:/Tools/fansMedalHelper/logintool/login.go:172 +0x19

**Comment by XiaoMiku01** [comment]
更换网络环境试试

**Comment by RnYi** [comment]
> 更换网络环境试试

好了，貌似是因为走了代理

**Comment by evpeople** [comment]
提议 login.go 进入for循环先进行sleep，可以部分避免这个panic
