### ISSUE TITLE
阿里云没权限/终端连不上github的解决方案

### ISSUE THREAD

**Issue by Sakuranda** [XiaoMiku01/fansMedalHelper#24]
萌新部署阿里云时遇到的问题（不知道对不对 反正这样搞后我能用了）
1：阿里云“您没有获取函数详情的权限”
    “请联系您的主账号为您添加fc:GetFunction权限，或者直接赋予您AliyunFCFullAccess的权限策略。”
解决方法：RAM访问控制—授权管理—授权—新建授权
授权主体：AliyunFCDefaultRole
授权策略名称：AdministratorAccess

2：终端里链接不上github 被墙了
解决方法：hosts添加下列两行
140.82.112.3 github.com
199.232.69.194 github.global.ssl.fastly.net

最后感谢下XiaoMiku01大佬做的新粉丝牌助手 cherrynmsl

**Comment by XiaoMiku01** [comment]
可以在文档的仓库里pr https://github.com/XiaoMiku01/fansMedalHelperVersion
