### ISSUE TITLE
能否增加白名单来打卡?

### ISSUE THREAD

**Issue by Notofnice** [XiaoMiku01/fansMedalHelper#3]
因为有挺多陈年老up的牌子放在那不想管，只想对几位经常关注的up自动打卡点赞
能从已有牌子的up中自行选择uid来打卡吗?

**Comment by XiaoMiku01** [comment]
加入了黑名单机制

**Comment by ToumaLover** [comment]
我fork的repo里修改成了按直播间号匹配白名单，你可以单独复制我对白名单匹配的修改
