### ISSUE TITLE
请问这样是我有问题吗？

### ISSUE THREAD

**Issue by ABlackx** [XiaoMiku01/fansMedalHelper#36]
![image](https://user-images.githubusercontent.com/103866959/171399788-40a7226f-56be-435b-b75f-d8a721b0a60a.png)

今天上去跑了几次都是这样，前几天则没有这个问题。

**Comment by ZippyRhys** [comment]
我也是报这个错。

**Comment by ABlackx** [comment]
好的好的，辛苦了
