### ISSUE TITLE
点赞、分享任务成功率判定有点问题

### ISSUE THREAD

**Issue by MianJu28** [XiaoMiku01/fansMedalHelper#37]
用了三四天了，发现点赞分享任务第一次执行的时候所有的牌子就已经1100亲密度以上了，但每次都还要重试4次才结束，是不是判定有点问题

**Comment by XiaoMiku01** [comment]
点赞加分享 一共是 1200 亲密度，为了尽量全部拿到，我判断了是否拿满1200 ，成功了百分之90的牌子或者重试超过10次才会退出

**Comment by MianJu28** [comment]
> 

好的，了解了
