### ISSUE TITLE
可以支持代理吗

### ISSUE THREAD

**Issue by RnYi** [XiaoMiku01/fansMedalHelper#38]
想用tg推送

**Comment by XiaoMiku01** [comment]
云函数可以选择地区，试试境外能不能推送出去，代理有空会加的

**Comment by XiaoMiku01** [comment]
已支持设置代理 配置文件中的 `PROXY` 参数设置代理地址，不过由于 aiohttp 库的限制，只支持 `http` 代理模式 ，可以拉取最新的代码测试一下

**Comment by RnYi** [comment]
> 已支持设置代理 配置文件中的 `PROXY` 参数设置代理地址，不过由于 aiohttp 库的限制，只支持 `http` 代理模式 ，可以拉取最新的代码测试一下

出现错误：
 `Cannot connect to host api.telegram.org:443 ssl:default [参数错误。]`

**Comment by RnYi** [comment]
> 已支持设置代理 配置文件中的 `PROXY` 参数设置代理地址，不过由于 aiohttp 库的限制，只支持 `http` 代理模式 ，可以拉取最新的代码测试一下

我用的v2rayN，打印的日志信息里显示确实收到了代理请求。推送用到的token和userid应该没问题，我试过。
![image](https://user-images.githubusercontent.com/19200146/171941221-a71aba6e-50ed-41bd-afbe-0e31bcb177e2.png)

**Comment by XiaoMiku01** [comment]
看了一下，tg 推送 api 似乎只支持 `https`  , aiohttp 库不支持 ，如果要解决还需要换其他的库，暂行先mark 一下

**Comment by XiaoMiku01** [comment]
目前已支持 `http`/`socks4`/`socks5` 三种代理协议  
更新代码后 需要额外安装 `aiohttp_socks` 库才能使用
```shell
pip3 install aiohttp_socks
```
