### ISSUE TITLE
请问这是什么情况？

### ISSUE THREAD

**Issue by daidaidayouxia** [XiaoMiku01/fansMedalHelper#39]
显示
DeprecationWarning: There is no current event loop

**Comment by XiaoMiku01** [comment]
能不能截图，这一行我能看出个什么

**Comment by daidaidayouxia** [comment]
私密马赛，
![habixia](https://user-images.githubusercontent.com/99523296/171791809-0861e04d-f90e-463c-b718-82ac43dbced1.png)

**Comment by XiaoMiku01** [comment]
Python版本是多少

**Comment by daidaidayouxia** [comment]
3.10

**Comment by XiaoMiku01** [comment]
将 `main.py`  112行改为  `loop = asyncio.new_event_loop()` 再在下面加一行 `asyncio.set_event_loop(loop)` ，如下：
```python 
    else:
        log.info('外部调用,开启任务')
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(main())
        log.info("任务结束")
```
保存运行试试

**Comment by daidaidayouxia** [comment]
运行无报错了，谢谢谢谢
