### ISSUE TITLE
可以加一个参数来指定配置文件的路径吗? ql每次更新配置都要恢复配置太麻烦了

### ISSUE THREAD

**Issue by FairyWorld** [XiaoMiku01/fansMedalHelper#42]
可以加一个参数来指定配置文件的路径吗? ql每次更新配置都要恢复配置太麻烦了, 如果没有参数用默认路径

例如: 
python main.py  xxx/config.yaml

**Comment by XiaoMiku01** [comment]
可以使用 Docker 方式的命令来启动，可以在环境变量中读取配置  ，参考 Docker 部署方式中，将 yaml 格式转换成 json 字符串，之后运行  
```shell
USERS='<转换后的配置json字符串>' python index.py
```
