### ISSUE TITLE
使用docker部署的情况下，启动时可能会因为users.yaml文件的冲突而无法更新

### ISSUE THREAD

**Issue by starrin** [XiaoMiku01/fansMedalHelper#44]
![TQS(5P%63SN09AO3A3R1 P0](https://user-images.githubusercontent.com/62949447/172280942-570d70df-30ba-4ebf-ac0f-9992f32e4e43.png)
如截图

**Comment by XiaoMiku01** [comment]
将 git pull  提前了。这次应该不会了dockerhub那边我去更新一下

**Comment by XiaoMiku01** [comment]
dockerhub 已推送

**Comment by starrin** [comment]
我看了下，感觉单纯提前git pull有点治标不治本，只能解决第一次启动时无法更新的问题，以后如果更新涉及到users.yaml的话还是会出问题的。
稳妥的做法是先git reset --hard回退掉对users.yaml的修改，然后再pull，然后再根据环境变量重新覆盖掉users.yaml文件
不过users.yaml应该不怎么会更新，也无所谓了

**Comment by PeanutMelonSeedBigAlmond** [comment]
其实我觉得可以将项目代码直接打包在镜像里面，将配置文件单独用数据卷挂载出来会比较好

稍微修改了一下dockerfile

![image](https://user-images.githubusercontent.com/25266280/172530641-c51a7bd3-d91b-448e-8d7d-e779f6984423.png)

**Comment by XiaoMiku01** [comment]
其实吧，直接删除容器就行。再run一个就行。。待会去改一下文档
