### ISSUE TITLE
开了代理，用 aiohttp 总是报错 Cannot connect to host discord.com:443 ssl:default [Connection reset by peer]

### ISSUE THREAD

**Issue by Huxzhi** [XiaoMiku01/fansMedalHelper#45]
![image](https://user-images.githubusercontent.com/49866441/172335919-0f5869ab-c7ad-4562-b20e-a84b505dde99.png)

如果用request 就没问题，然后 markdown False 没起作用

**Comment by XiaoMiku01** [comment]
代理问题没完全解决，暂时没空

**Comment by XiaoMiku01** [comment]
#38
