### ISSUE TITLE
点赞分享模块成功率异常

### ISSUE THREAD

**Issue by Radekyspec** [XiaoMiku01/fansMedalHelper#51]
## 账号状况及设置
粉丝牌46个，10个大航海牌（21级或以上），无20级牌子

使用CORN，每日0点5分运行一次

异步执行开启

### 第一次分享：
0个牌子获得大于1200亲密度，全部非大航海牌子（36个）都已经获得1100亲密度，0个牌子获取少于1100亲密度

触发重试机制，开始重新执行点赞分享任务

### 之后的分享：
每一次都是所有20级以下牌子获得1100亲密度，无牌子获得大于1200或者小于1100

不断重试，直到超出重试范围，点赞分享任务结束

## 原因分析
可能是由于`./src/user.py`的第`131行`的判断条件异常

```shell
if len(finallyMedals) / len(self.medalsLower20) <= 0.9:
```

通过3次点赞（600）+ 5次分享（500），在不发送打卡弹幕和未达到在线观看时长的情况下，一共只能获得1100亲密度。但此处判断为大于等于1200亲密度的牌子（只能为0），导致错误的判断了成功率

可以改为：
```shell
if len(midMedals) / len(self.medalsLower20) <= 0.9:
```

或者

```shell
if len(failedMedals) / len(self.medalsLower20) >= 0.9:
```

**Comment by XiaoMiku01** [comment]
看了一下，只需将  src/user.py line 120 改为
```python
finallyMedals = [medla for medla in self.medalsLower20 if medal['medal']['today_feed'] >= 1100]
```
即可，感谢纠错

**Comment by Radekyspec** [comment]
这样会不会跟midMedals重复啊（

**Comment by XiaoMiku01** [comment]
> 这样会不会跟midMedals重复啊（

阿这，好像是的，我再看看🤣

**Comment by XiaoMiku01** [comment]
哦 其实 midMedals 没有存在的必要，删了
