### ISSUE TITLE
疑是直播心跳只对短id有效

### ISSUE THREAD

**Issue by catlair** [XiaoMiku01/fansMedalHelper#54]
部分主播有两个直播间id，如冷鸟的id是47377，同时还有个短id 593（正常浏览时会重定向到短id），使用普通长id无法获取到100亲密度，使用短id可以。

https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel 获取到的是长id。

https://github.com/XiaoMiku01/fansMedalHelper/blob/b144e2ed94c3c035ba44bd573f772738a8f60353/src/api.py#L141

**Comment by XiaoMiku01** [comment]
是最近没获取到吗？前几天都能，难道最近改了必须短号？

**Comment by catlair** [comment]
等我再观察一下

**Comment by XiaoMiku01** [comment]
没问题，长号发心跳依然可以拿到亲密度，前几天是叔叔抽风了，导致亲密度缺失
