### ISSUE TITLE
表示不知道是我的原因还是又改规则了

### ISSUE THREAD

**Issue by Malus-Mill** [XiaoMiku01/fansMedalHelper#55]
如题、只打卡了200个勋章；
而且只能同步打卡，发弹幕和30分钟还没测试
![image](https://user-images.githubusercontent.com/53999738/173234825-ca07a177-e0e8-4fb2-b562-d80b7073a054.png)
![image](https://user-images.githubusercontent.com/53999738/173234872-3db9ff37-986a-4ac0-8283-d530226d39fc.png)

**Comment by XiaoMiku01** [comment]
叔叔脑子抽了，现在有风控

**Comment by Malus-Mill** [comment]
> 叔叔脑子抽了，现在有风控

表示有风控了、表示要加个查询、记录、再开功能吗?

**Comment by XiaoMiku01** [comment]
风控后这一天走啥任务都不加亲密度了。无解
