### ISSUE TITLE
Bark推送能否使用自建Bark服务器

### ISSUE THREAD

**Issue by ssyximmlove** [XiaoMiku01/fansMedalHelper#58]
Bark推送能否使用自建Bark服务器

**Comment by SuperPung** [comment]
可以的，只需要在 `{"notifier":"bark","params":{"markdown":False,"key":"xxxxxx"}}` 的 `"key"` 中填写完整的 URL 即可。

具体参见：

https://github.com/XiaoMiku01/fansMedalHelper/blob/1e9e85260d16e92a1718ba17fe89b6f9b9b338ff/onepush/providers/bark.py#L23-L27
