### ISSUE TITLE
定时运行的bug

### ISSUE THREAD

**Issue by HYY-zh** [XiaoMiku01/fansMedalHelper#60]
挂服务器上的，基本每隔几天就会遇到这样的情况，感觉是bug？

![截图_2022-06-15_00-34-04](https://user-images.githubusercontent.com/61227595/173631820-f8fdc25e-a698-4ed7-9c32-5ac228c63abe.png)

环境：python3.10.4；windows server 2016 datacenter

**Comment by ckeleshi** [comment]
我是在main.py调用schedulers.add_job()的时候加上misfire_grace_time参数解决的
