### ISSUE TITLE
粉丝牌的规则又双叒叕改啦！

### ISSUE THREAD

**Issue by LTZDLY** [XiaoMiku01/fansMedalHelper#67]
貌似是今天改的，现在的规则描述如下：

> 在直播间内可通过以下任务获得亲密度：
> - 给主播点赞：每日首次可获得100亲密度
> - 发送弹幕：每日首次可获得100亲密度
> - 观看直播：每观看五分钟可获得100亲密度
> - 投喂银瓜子礼物：100银瓜子=1亲密度
> - 投喂电池礼物/醒目留言：1电池=50亲密度

观看直播获得的亲密度上限取消，也就是说每天光看直播就可以直接拿满1500亲密度。

不过根据今天的使用情况来看，一整套下来还是1300亲密度不变，并没有感觉到除了观看直播上限增加以外的差别，不知道叔叔到底是怎么改的。随便进一个1300亲密度的房间，观看10分钟后牌子确实到1500，整挺好。

**Comment by ZippyRhys** [comment]
我是最近开始一直没法过1000甚至是0亲密度，不知道和这个规则改动有没有关系，总之我蒙古

**Comment by XiaoMiku01** [comment]
知道了，明天测试一下没问题，就更新

**Comment by XiaoMiku01** [comment]
已更新

**Comment by Miao2z** [comment]
> 已更新

感谢大佬。现在好像只刷观看时长就能刷满1500，请教一下，怎么关闭弹幕打卡呢？
