### ISSUE TITLE
任务完成后直播间的亲密度丢失，出现只有 200 的情况

### ISSUE THREAD

**Issue by XiaoMiku01** [XiaoMiku01/fansMedalHelper#69]
B站亲密度结算有延迟，可能长达几个小时才会显示出来。

**Comment by yooooo00** [comment]
b站更新后，0.3.4版本每人可获取800亲密度、0.3.5版本每人仅可获取200亲密度，似乎均无法获取满1500亲密度、不是结算延迟的原因？

**Comment by XiaoMiku01** [comment]
慢慢等，可以拿满

**Comment by yooooo00** [comment]
似乎是因为旧版本配置文件中WATCHINGLIVE项值仅为是否观看直播，新版本值则用来确定观看时长。如果原封不动使用旧版本配置文件（WATCHINGLIVE值为1）就会导致仅观看1分钟，也就只获得打卡、分享的200亲密度。

**Comment by MisayaSEEDsky** [comment]
> 似乎是因为旧版本配置文件中WATCHINGLIVE项值仅为是否观看直播，新版本值则用来确定观看时长。如果原封不动使用旧版本配置文件（WATCHINGLIVE值为1）就会导致仅观看1分钟，也就只获得打卡、分享的200亲密度。

`HEART_MAX = self.config['WATCHINGLIVE']
 self.log.log("INFO", f"每日{HEART_MAX}分钟任务开始")`

WATCHINGLIVE确实是确定观看时长。
