### ISSUE TITLE
最近是不是容易被风控，我的号天天要重新登陆

### ISSUE THREAD

**Issue by 1563652588** [XiaoMiku01/fansMedalHelper#71]
rtrt qq群又没了

**Comment by FairyWorld** [comment]
我也是

**Comment by 1563652588** [comment]
> 我也是

我号又下线了，挂脚本的缘故

**Comment by FairyWorld** [comment]
> > 我也是
> 
> 我号又下线了，挂脚本的缘故

21.45，我掉了。存活时间不到2个小时

**Comment by 1563652588** [comment]
> > > 我也是
> > 
> > 
> > 我号又下线了，挂脚本的缘故
> 
> 21.45，我掉了。存活时间不到2个小时

关脚本吧 不然晓老师这个云函数还得不停扫码

**Comment by XiaoMiku01** [comment]
？这个项目也会掉？

**Comment by 1563652588** [comment]
> 
这个没掉 我目前测试发现是油猴的问题

**Comment by FairyWorld** [comment]
> ？这个项目也会掉？

我也发现不是这个脚本的原因，目前只知道在github action跑其他脚本会掉线
