### ISSUE TITLE
能否完成任务后佩戴指定粉丝牌子

### ISSUE THREAD

**Issue by Rayzggz** [XiaoMiku01/fansMedalHelper#72]
现在的 WEARMEDAL  是否弹幕打卡时自动带上当前房间的粉丝牌 功能开启后
结束任务后佩戴的牌子是最后执行的直播间的牌子

能否新增一个设置就是全部任务执行完任务后佩戴指定的牌子

**Comment by XiaoMiku01** [comment]
已更新，现在的逻辑是，任务完成后自动带回原来的牌子
