### ISSUE TITLE
部分直播间没有完成打卡

### ISSUE THREAD

**Issue by QingM0** [XiaoMiku01/fansMedalHelper#73]
有亲密度但牌子是灰的（应该是没打卡） 错误日志也没报（不清楚还需要提供什么信息   ~~导致要算命~~ 私密马赛）
![Screenshot_2022-07-24-06-33-09-072_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/79330164/180625128-6003bda6-e2ef-49d6-9e34-1513f00b4467.jpg)
![Screenshot_2022-07-24-06-39-11-391_org.telegram.messenger.web.png](https://user-images.githubusercontent.com/79330164/180625175-2f2b109a-7464-4a89-8c71-321e7ca3b78b.png)

**Comment by XiaoMiku01** [comment]
手动打卡是否能点亮

**Comment by XiaoMiku01** [comment]
他们直播间 `.` 点是屏蔽词 ,我在每条打卡弹幕后都加了一个 `.`   ,已经简单修复了一下，更新一下代码吧

**Comment by QingM0** [comment]
> 手动打卡是否能点亮

之前没有注意消息 可以

**Comment by QingM0** [comment]
> 他们直播间 `.` 点是屏蔽词 ,我在每条打卡弹幕后都加了一个 `.`   ,已经简单修复了一下，更新一下代码吧

红豆泥阿里嘎多
