### ISSUE TITLE
是我铸币了吗

### ISSUE THREAD

**Issue by Spring0323** [XiaoMiku01/fansMedalHelper#74]
![QQ截图20220724124321](https://user-images.githubusercontent.com/97651950/180632581-2f47e3a3-f509-4821-bd15-5f0682590a07.png)

**Comment by XiaoMiku01** [comment]
看看你复制的填的环境变量，记得access_key打码

**Comment by Spring0323** [comment]
![QQ截图20220724125450](https://user-images.githubusercontent.com/97651950/180632816-112816d1-3f3d-4617-aa04-6d1f4dffc279.png)

**Comment by XiaoMiku01** [comment]
把DANMAKU_CD  后面的 0 外面的  `“”`  双引号删了  ，点重新部署

**Comment by Spring0323** [comment]
谢谢大佬 mua~
