### ISSUE TITLE
typo in /src/user.py

### ISSUE THREAD

**Issue by DurganShelley** [XiaoMiku01/fansMedalHelper#76]
![image](https://user-images.githubusercontent.com/67219840/180970811-8465a8ea-997b-4b24-b4bf-95edd2b06cc3.png)

self.log.log("SUCCESS", f"每日{HEART_MAX}分钟任务开始")

→→→

self.log.log("SUCCESS", f"每日{HEART_MAX}分钟任务完成")

**Comment by XiaoMiku01** [comment]
fixed,thx
