### ISSUE TITLE
表示CD好像又加回来了。还有，点赞的时候好像就算发送弹幕了

### ISSUE THREAD

**Issue by Malus-Mill** [XiaoMiku01/fansMedalHelper#8]
![image](https://user-images.githubusercontent.com/53999738/170399553-a3650f52-53d6-4a6f-ba3b-ce8c0e6f201c.png)

**Comment by XiaoMiku01** [comment]
诶。真的假的

**Comment by Huli-fox** [comment]
草，500多个牌子  
我这边刚试了下每次重试完成4个任务，重试几次就全部完成了  
如图  
![屏幕截图 2022-05-26 113519.png](https://s2.loli.net/2022/05/26/A4Q2KmW85rxyPHh.png)

**Comment by XiaoMiku01** [comment]
> 草，500多个牌子  
> 我这边刚试了下每次重试完成4个任务，重试几次就全部完成了  
> 如图  
> ![屏幕截图 2022-05-26 113519.png](https://s2.loli.net/2022/05/26/A4Q2KmW85rxyPHh.png)  

所以现在到底有没有CD？

**Comment by Malus-Mill** [comment]
![image](https://user-images.githubusercontent.com/53999738/170414513-139d132b-a96b-47a2-aabf-8d7dbad01e92.png)
![image](https://user-images.githubusercontent.com/53999738/170414556-a9fa2ff2-d7c3-47df-95bb-07feb10de5d3.png)

刚刚试的，建议还是加上吧、还有像问一下、怎么把弹幕打卡关掉啊

**Comment by Malus-Mill** [comment]
要不加上设置CD选项试试？

**Comment by XiaoMiku01** [comment]
> 要不加上设置CD选项试试？
> 

可以，回头我看看

**Comment by Huli-fox** [comment]
> > 草，500多个牌子
> > 我这边刚试了下每次重试完成4个任务，重试几次就全部完成了
> > 如图
> > ![屏幕截图 2022-05-26 113519.png](https://camo.githubusercontent.com/5552d8802108db0222623041329822da38a64a9395d8605ea57e10dd4ced95fc/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f32362f413451324b6d5738357278795048682e706e67)
> 
> 所以现在到底有没有CD？

我这边20个牌子两三分钟就完成了，没有CD  
牌子多的话不太清楚

**Comment by Malus-Mill** [comment]
> > 要不加上设置CD选项试试？
> 
> 可以，回头我看看

感谢大佬！

**Comment by Malus-Mill** [comment]
![image](https://user-images.githubusercontent.com/53999738/170417900-99592de5-9922-40b9-8a85-9c3110d8169a.png)
如图、表示都打上了、但是有部分没打满、会不会是输出显示的问题？

> > 要不加上设置CD选项试试？
> 
> 可以，回头我看看

**Comment by Malus-Mill** [comment]
好像黑名单没生效？

**Comment by XiaoMiku01** [comment]
> 

目前看来是异步执行太快导致部分点赞分享被B站吞了的原因。事实上大部分都是1100以上。黑名单也没问题，我刚刚测试了。填写时候注意格式，和英文冒号和逗号，后续版本会迭代 用户自行设置同步异步和CD和任务开关
