### ISSUE TITLE
表示可以把牌子多的分成200、150之类的一批一批的执行吗?

### ISSUE THREAD

**Issue by Malus-Mill** [XiaoMiku01/fansMedalHelper#81]
如题，表示牌子快上600了，表示大佬可以支持分批打卡吗

**Comment by XiaoMiku01** [comment]
前几天测了一下，分批的话，所有牌子亲密度全卡在300了。解决方法没找到

**Comment by pjy612** [comment]
100出头的咱 瑟瑟发抖。。。这样也 每次基本跑1个小时...

**Comment by realYXT** [comment]
我也，300多个牌子，亲密度也是卡在300多了。。。www

**Comment by dandandashi** [comment]
同 400牌子 后面的基本就灰0亲密度了
