### ISSUE TITLE
更多推送不会配置

### ISSUE THREAD

**Issue by shiroringo** [XiaoMiku01/fansMedalHelper#83]
配置更多推送的时候，显示MOREPUSH参数错误。钉钉机器人有两个密钥，但是token值示例里只有一个，是不是哪里不对

**Comment by Banana-Uncle** [comment]
阿里云这边新办法用配置工具好像确实无法配置MOREPUSH，不知道应该用什么格式配置？

**Comment by XiaoMiku01** [comment]
把配置文件里的 `False` 改成小写 `false`
