### ISSUE TITLE
最近B站出了每天能领1电池活动，能加上自动领取吗？

### ISSUE THREAD

**Issue by Yuiffy** [XiaoMiku01/fansMedalHelper#88]
每天发5条弹幕后可以领1电池

**Comment by XiaoMiku01** [comment]
不是1电池？

**Comment by Yuiffy** [comment]
> 不是1电池？

确实，我弄错了，编辑了

**Comment by XiaoMiku01** [comment]
[3d3e7bd](https://github.com/XiaoMiku01/fansMedalHelper/commit/3d3e7bde9f3c8cb6c87137a15412eaa6fdc0d975) 试试，我没测试，不知道成不成

**Comment by Yuiffy** [comment]
> [3d3e7bd](https://github.com/XiaoMiku01/fansMedalHelper/commit/3d3e7bde9f3c8cb6c87137a15412eaa6fdc0d975) 试试，我没测试，不知道成不成

试了下，成功了
