### ISSUE TITLE
最近经常弹幕打卡任务不能完成是为什么呢

### ISSUE THREAD

**Issue by Nuit5566** [XiaoMiku01/fansMedalHelper#90]
应援团签到也会失败
试过切换异步同步都会出现这个现象

**Comment by Nuit5566** [comment]
![E46A639252421EF3C0D4F6A7ED4E3CF1](https://user-images.githubusercontent.com/63411237/200178939-1a3207e9-f36f-45af-850f-1e0421b29521.jpg)

**Comment by vigi1090** [comment]
同问
