### ISSUE TITLE
Python 3.11 适配请求

### ISSUE THREAD

**Issue by CaSiOFT** [XiaoMiku01/fansMedalHelper#92]
如题。Python 3.11中禁止了将coroutine对象直接传递至asyncio.wait以进行异步执行的做法。（见官方文档说明[Coroutines and Tasks](https://docs.python.org/3/library/asyncio-task.html) 中 [Waiting Primitives](https://docs.python.org/3/library/asyncio-task.html#id10)一节的说法“Changed in version 3.11: Passing coroutine objects to wait() directly is forbidden.”）

项目文件"src/user.py"的205及206行中，有将coroutine对象直接送入asyncio.wait的做法，这样会产生报错”Passing coroutines is forbidden, use tasks explicitly.“

这导致了在Python 3.11环境下程序无法运行，请求进行Python 3.11的适配，谢谢。

**Comment by Loongphy** [comment]
Fixed https://github.com/XiaoMiku01/fansMedalHelper/commit/8d52318223248f7dc792a5586a556cf48c748f3c
