### ISSUE TITLE
添加新功能-领取电池

### ISSUE THREAD

**Issue by shengetui** [XiaoMiku01/fansMedalHelper#94]
每天直播间发表评论五次后可以领取1电池，
api接口：
`https://api.live.bilibili.com/xlive/app-ucenter/v1/userTask/UserTaskReceiveRewards`
参数：
`    data = {

            "access_key": "xxxxxxxxxxxxxx",
            "actionKey": "appkey",
            "appkey": "xxxxxxxxxxxxx",
            "build": 70400100,
            "c_locale": "zh-Hans_CN",
            "device": "phone",
            "disable_rcmd": 0,
            "mobi_app": "iphone",
            "platform": "ios",
            "s_locale": "zh-Hans_CN",
            "sign": "xxxxx",
            "statistics": "%7B%22appId%22%3A1%2C%22version%22%3A%227.4.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D",
            "target_id": 672342685,
            "ts": int(time.time())
    }`

**Comment by shengetui** [comment]
> 每天直播间发表评论五次后可以领取1电池， api接口： `https://api.live.bilibili.com/xlive/app-ucenter/v1/userTask/UserTaskReceiveRewards` 参数： ` data = {
> 
> ```
>         "access_key": "xxxxx",
>         "actionKey": "appkey",
>         "appkey": "xxxxx",
>         "build": 70400100,
>         "c_locale": "zh-Hans_CN",
>         "device": "phone",
>         "disable_rcmd": 0,
>         "mobi_app": "iphone",
>         "platform": "ios",
>         "s_locale": "zh-Hans_CN",
>         "sign": "xxxxx",
>         "statistics": "%7B%22appId%22%3A1%2C%22version%22%3A%227.4.0%22%2C%22abtest%22%3A%22%22%2C%22platform%22%3A1%7D",
>         "target_id": 672342685,
>         "ts": int(time.time())
> }`
> ```

**Comment by XiaoMiku01** [comment]
近期会一起更新，正在解决其他的问题，别急

**Comment by XiaoMiku01** [comment]
[3d3e7bd](https://github.com/XiaoMiku01/fansMedalHelper/commit/3d3e7bde9f3c8cb6c87137a15412eaa6fdc0d975) 试试看，我没测试，不知道行不行

**Comment by shengetui** [comment]
> 

呃呃,可以,很好
