### ISSUE TITLE
点赞、分享任务是否成功的检测逻辑

### ISSUE THREAD

**Issue by gin3715** [XiaoMiku01/fansMedalHelper#97]
https://github.com/XiaoMiku01/fansMedalHelper/blob/3d3e7bde9f3c8cb6c87137a15412eaa6fdc0d975/src/user.py#L98-L107

https://github.com/XiaoMiku01/fansMedalHelper/blob/3d3e7bde9f3c8cb6c87137a15412eaa6fdc0d975/src/user.py#L141-L143

点赞分享可以单独手动配置是否开启，但是判定成功的亲密度阈值为固定的200，而没有跟随配置变化，在**只开启一个**时可能会导致反复重试。

**Comment by XiaoMiku01** [comment]
当时写的时候分享和点赞写在一起了，每次都会增加100亲密度，感觉没什么区别，而且点赞和分享都是直接调用的接口，并不会发送点赞弹幕，主播应该看不到
